//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Categorie
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Categorie()
    {
        this.Retetas = new HashSet<Reteta>();
    }

    public double categ_id { get; set; }
    public string tip { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Reteta> Retetas { get; set; }
}

public partial class Ingredient
{
    public Nullable<double> ingred_id { get; set; }
    public string ingredient1 { get; set; }

    public virtual Set_ingrediente Set_ingrediente { get; set; }
}

public partial class Reteta
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Reteta()
    {
        this.Set_ingrediente = new HashSet<Set_ingrediente>();
    }

    public double reteta_id { get; set; }
    public string nume { get; set; }
    public string descriere { get; set; }
    public Nullable<double> categ_id { get; set; }
    public string vegetariana { get; set; }
    public Nullable<double> timp_preparare { get; set; }
    public Nullable<int> portii { get; set; }
    public string sursa { get; set; }

    public virtual Categorie Categorie { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Set_ingrediente> Set_ingrediente { get; set; }
}

public partial class Set_ingrediente
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Set_ingrediente()
    {
        this.Ingredients = new HashSet<Ingredient>();
    }

    public Nullable<double> reteta_id { get; set; }
    public double ingred_id { get; set; }
    public Nullable<double> cantitate { get; set; }
    public string um { get; set; }
    public string comentarii { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Ingredient> Ingredients { get; set; }
    public virtual Reteta Reteta { get; set; }
}
