//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Web.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reteta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reteta()
        {
            this.Set_ingrediente = new HashSet<Set_ingrediente>();
        }
    
        public double reteta_id { get; set; }
        public string nume { get; set; }
        public string descriere { get; set; }
        public Nullable<double> categ_id { get; set; }
        public string vegetariana { get; set; }
        public Nullable<double> timp_preparare { get; set; }
        public Nullable<int> portii { get; set; }
        public string sursa { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Set_ingrediente> Set_ingrediente { get; set; }
    }
}
