//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Wpf.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Nullable<double> ingred_id { get; set; }
        public string ingredient1 { get; set; }
    
        public virtual Set_ingrediente Set_ingrediente { get; set; }
    }
}
